package com.github.yoshio.mapper;

import com.github.yoshio.mybatis.domain.Pet;
import com.github.yoshio.mybatis.domain.PetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int countByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int deleteByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int deleteByPrimaryKey(Integer petid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int insertSelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    List<Pet> selectByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    Pet selectByPrimaryKey(Integer petid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int updateByExampleSelective(@Param("record") Pet record, @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int updateByExample(@Param("record") Pet record, @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int updateByPrimaryKeySelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PET
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    int updateByPrimaryKey(Pet record);
}