package com.github.yoshio.mybatis.domain;

public class Owner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.OWNER.OWNERNAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    private String ownername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.OWNER.OWNERNAME
     *
     * @return the value of PUBLIC.OWNER.OWNERNAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.OWNER.OWNERNAME
     *
     * @param ownername the value for PUBLIC.OWNER.OWNERNAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }
}