package com.github.yoshio.mybatis.domain;

import java.util.Date;

public class Pet {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.PET.PETID
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	private Integer petid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.PET.PETNAME
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	private String petname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.PET.OWNERNAME
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	private String ownername;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.PET.PRICE
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column PUBLIC.PET.BIRTHDATE
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	private Date birthdate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.PET.PETID
	 * @return  the value of PUBLIC.PET.PETID
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public Integer getPetid() {
		return petid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.PET.PETID
	 * @param petid  the value for PUBLIC.PET.PETID
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void setPetid(Integer petid) {
		this.petid = petid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.PET.PETNAME
	 * @return  the value of PUBLIC.PET.PETNAME
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public String getPetname() {
		return petname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.PET.PETNAME
	 * @param petname  the value for PUBLIC.PET.PETNAME
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void setPetname(String petname) {
		this.petname = petname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.PET.OWNERNAME
	 * @return  the value of PUBLIC.PET.OWNERNAME
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public String getOwnername() {
		return ownername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.PET.OWNERNAME
	 * @param ownername  the value for PUBLIC.PET.OWNERNAME
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void setOwnername(String ownername) {
		this.ownername = ownername;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.PET.PRICE
	 * @return  the value of PUBLIC.PET.PRICE
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.PET.PRICE
	 * @param price  the value for PUBLIC.PET.PRICE
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column PUBLIC.PET.BIRTHDATE
	 * @return  the value of PUBLIC.PET.BIRTHDATE
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public Date getBirthdate() {
		return birthdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column PUBLIC.PET.BIRTHDATE
	 * @param birthdate  the value for PUBLIC.PET.BIRTHDATE
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}
}