package com.github.yoshio.mybatis.domain;

import java.util.ArrayList;
import java.util.List;

public class ShopExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public ShopExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andShopIdIsNull() {
			addCriterion("SHOP_ID is null");
			return (Criteria) this;
		}

		public Criteria andShopIdIsNotNull() {
			addCriterion("SHOP_ID is not null");
			return (Criteria) this;
		}

		public Criteria andShopIdEqualTo(String value) {
			addCriterion("SHOP_ID =", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotEqualTo(String value) {
			addCriterion("SHOP_ID <>", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThan(String value) {
			addCriterion("SHOP_ID >", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_ID >=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThan(String value) {
			addCriterion("SHOP_ID <", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLessThanOrEqualTo(String value) {
			addCriterion("SHOP_ID <=", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdLike(String value) {
			addCriterion("SHOP_ID like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotLike(String value) {
			addCriterion("SHOP_ID not like", value, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdIn(List<String> values) {
			addCriterion("SHOP_ID in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotIn(List<String> values) {
			addCriterion("SHOP_ID not in", values, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdBetween(String value1, String value2) {
			addCriterion("SHOP_ID between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopIdNotBetween(String value1, String value2) {
			addCriterion("SHOP_ID not between", value1, value2, "shopId");
			return (Criteria) this;
		}

		public Criteria andShopPassIsNull() {
			addCriterion("SHOP_PASS is null");
			return (Criteria) this;
		}

		public Criteria andShopPassIsNotNull() {
			addCriterion("SHOP_PASS is not null");
			return (Criteria) this;
		}

		public Criteria andShopPassEqualTo(String value) {
			addCriterion("SHOP_PASS =", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassNotEqualTo(String value) {
			addCriterion("SHOP_PASS <>", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassGreaterThan(String value) {
			addCriterion("SHOP_PASS >", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_PASS >=", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassLessThan(String value) {
			addCriterion("SHOP_PASS <", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassLessThanOrEqualTo(String value) {
			addCriterion("SHOP_PASS <=", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassLike(String value) {
			addCriterion("SHOP_PASS like", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassNotLike(String value) {
			addCriterion("SHOP_PASS not like", value, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassIn(List<String> values) {
			addCriterion("SHOP_PASS in", values, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassNotIn(List<String> values) {
			addCriterion("SHOP_PASS not in", values, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassBetween(String value1, String value2) {
			addCriterion("SHOP_PASS between", value1, value2, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopPassNotBetween(String value1, String value2) {
			addCriterion("SHOP_PASS not between", value1, value2, "shopPass");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNull() {
			addCriterion("SHOP_NAME is null");
			return (Criteria) this;
		}

		public Criteria andShopNameIsNotNull() {
			addCriterion("SHOP_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andShopNameEqualTo(String value) {
			addCriterion("SHOP_NAME =", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotEqualTo(String value) {
			addCriterion("SHOP_NAME <>", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThan(String value) {
			addCriterion("SHOP_NAME >", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameGreaterThanOrEqualTo(String value) {
			addCriterion("SHOP_NAME >=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThan(String value) {
			addCriterion("SHOP_NAME <", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLessThanOrEqualTo(String value) {
			addCriterion("SHOP_NAME <=", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameLike(String value) {
			addCriterion("SHOP_NAME like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotLike(String value) {
			addCriterion("SHOP_NAME not like", value, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameIn(List<String> values) {
			addCriterion("SHOP_NAME in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotIn(List<String> values) {
			addCriterion("SHOP_NAME not in", values, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameBetween(String value1, String value2) {
			addCriterion("SHOP_NAME between", value1, value2, "shopName");
			return (Criteria) this;
		}

		public Criteria andShopNameNotBetween(String value1, String value2) {
			addCriterion("SHOP_NAME not between", value1, value2, "shopName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table PUBLIC.SHOP
	 * @mbggenerated  Mon Nov 12 13:46:19 JST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PUBLIC.SHOP
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 12 10:48:35 JST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}