package com.github.yoshio.mybatis.domain;

public class Shop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.SHOP_ID
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    private String shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.SHOP_PASS
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    private String shopPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOP.SHOP_NAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    private String shopName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.SHOP_ID
     *
     * @return the value of PUBLIC.SHOP.SHOP_ID
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.SHOP_ID
     *
     * @param shopId the value for PUBLIC.SHOP.SHOP_ID
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public void setShopId(String shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.SHOP_PASS
     *
     * @return the value of PUBLIC.SHOP.SHOP_PASS
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public String getShopPass() {
        return shopPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.SHOP_PASS
     *
     * @param shopPass the value for PUBLIC.SHOP.SHOP_PASS
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public void setShopPass(String shopPass) {
        this.shopPass = shopPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOP.SHOP_NAME
     *
     * @return the value of PUBLIC.SHOP.SHOP_NAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOP.SHOP_NAME
     *
     * @param shopName the value for PUBLIC.SHOP.SHOP_NAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }
}