package com.github.yoshio.mybatis.domain;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.ID
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.USERNAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.USER.PASSWORD
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.ID
     *
     * @return the value of PUBLIC.USER.ID
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.ID
     *
     * @param id the value for PUBLIC.USER.ID
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.USERNAME
     *
     * @return the value of PUBLIC.USER.USERNAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.USERNAME
     *
     * @param username the value for PUBLIC.USER.USERNAME
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.USER.PASSWORD
     *
     * @return the value of PUBLIC.USER.PASSWORD
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.USER.PASSWORD
     *
     * @param password the value for PUBLIC.USER.PASSWORD
     *
     * @mbggenerated Mon Nov 12 10:48:35 JST 2012
     */
    public void setPassword(String password) {
        this.password = password;
    }
}