package com.github.yoshio.mybatis.mapper;

import com.github.yoshio.mybatis.domain.Owner;
import com.github.yoshio.mybatis.domain.OwnerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OwnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    int countByExample(OwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    int deleteByExample(OwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    int deleteByPrimaryKey(String ownername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    int insert(Owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    int insertSelective(Owner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    List<Owner> selectByExample(OwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    int updateByExampleSelective(@Param("record") Owner record, @Param("example") OwnerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.OWNER
     *
     * @mbggenerated Mon Nov 12 13:46:19 JST 2012
     */
    int updateByExample(@Param("record") Owner record, @Param("example") OwnerExample example);
}